apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: sorteador-virtualservice
  namespace: ${NAMESPACE}
spec:
  hosts:
    - "sorteador-k8s.fabiobartoli.com.br"
  gateways:
    - sorteador-gateway
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: sorteador-service.${NAMESPACE}.svc.cluster.local
            port:
              number: 80
